java_library(
    name = "reactive-streams",
    exports = [
        "//external:jar/org/reactivestreams/reactive-streams"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


