java_library(
    name = "jakarta-transaction-api",
    exports = [
        "//external:jar/jakarta/transaction/jakarta-transaction-api"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


