java_library(
  name = "router",
  srcs = glob(["Router.java"]),
  deps = [
      "//dependencies/maven/artifacts/com/typesafe/akka:akka-actor-2-12",
      "//dependencies/maven/artifacts/com/typesafe/akka:akka-actor-typed-2-12",
      "//dependencies/maven/artifacts/com/typesafe/akka:akka-stream-2-12",
        "//dependencies/maven/artifacts/com/typesafe/play:play-2-12",
        "//dependencies/maven/artifacts/com/typesafe/play:play-java-2-12",
        "//dependencies/maven/artifacts/com/typesafe/play:play-server-2-12",
        "//dependencies/maven/artifacts/com/typesafe/play:play-streams-2-12",
        "//dependencies/maven/artifacts/com/typesafe/play:twirl-api-2-12",
        "//dependencies/maven/artifacts/com/fasterxml/jackson/core:jackson-databind",
        "//dependencies/maven/artifacts/com/fasterxml/jackson/core:jackson-core"
  ],
  visibility = ["//visibility:public"]
)

