java_library(
    name = "jakarta-activation-api",
    exports = [
        "//external:jar/jakarta/activation/jakarta-activation-api"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


