java_library(
    name = "jjwt",
    exports = [
        "//external:jar/io/jsonwebtoken/jjwt"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/fasterxml/jackson/core:jackson-databind"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


