java_library(
    name = "guice",
    exports = [
        "//external:jar/com/google/inject/guice"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/aopalliance:aopalliance",
        "//dependencies/maven/artifacts/com/google/guava:guava",
        "//dependencies/maven/artifacts/javax/inject:javax-inject"
    ],
    visibility = [
        "//visibility:public"
    ]
)


