java_library(
    name = "jackson-datatype-jdk8",
    exports = [
        "//external:jar/com/fasterxml/jackson/datatype/jackson-datatype-jdk8"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/fasterxml/jackson/core:jackson-core",
        "//dependencies/maven/artifacts/com/fasterxml/jackson/core:jackson-databind"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)



java_library(
    name = "jackson-datatype-jsr310",
    exports = [
        "//external:jar/com/fasterxml/jackson/datatype/jackson-datatype-jsr310"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/fasterxml/jackson/core:jackson-annotations",
        "//dependencies/maven/artifacts/com/fasterxml/jackson/core:jackson-core",
        "//dependencies/maven/artifacts/com/fasterxml/jackson/core:jackson-databind"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


