java_library(
    name = "guice-assistedinject",
    exports = [
        "//external:jar/com/google/inject/extensions/guice-assistedinject"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/google/inject:guice"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


