java_library(
    name = "jackson-dataformat-cbor",
    exports = [
        "//external:jar/com/fasterxml/jackson/dataformat/jackson-dataformat-cbor"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/com/fasterxml/jackson/core:jackson-core"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


