java_library(
    name = "jakarta-xml-bind-api",
    exports = [
        "//external:jar/jakarta/xml/bind/jakarta-xml-bind-api"
    ],
    runtime_deps = [
        "//dependencies/maven/artifacts/jakarta/activation:jakarta-activation-api"
    ],
    visibility = [
        "//dependencies/maven/artifacts:__subpackages__"
    ]
)


